name: Daily Scraper

on:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 9 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install Chrome
        run: |
          wget -qO- https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome-keyring.gpg
          echo 'deb [signed-by=/usr/share/keyrings/google-chrome-keyring.gpg] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt update
          sudo apt install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          CHROME_VERSION=$(chromium-browser --version | grep -oP '[0-9]+\.[0-9]+\.[0-9]+')  
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || echo "ERROR")

          if [[ "$CHROMEDRIVER_VERSION" == "ERROR" ]]; then
            echo "Could not find matching ChromeDriver version. Using latest stable version."
            CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          fi

          echo "Installing ChromeDriver version $CHROMEDRIVER_VERSION"
          wget -N "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
  
  
  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set Environment Variables from GitHub Secrets
        run: |
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Start Xvfb
        run: Xvfb :99 -screen 0 1024x768x16 &

      - name: Run the script
        env:
          DISPLAY: ":99"  # Required for Selenium in headless mode
        run: python pelosi_trader.py
