name: Daily Scraper

on:
  schedule:
    - cron: "0 9 * * *"  # Runs daily at 9 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          sudo apt-get update
          pip install -r requirements.txt

      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable  # You can specify a version if needed

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: latest  # Automatically matches Chrome

      - name: Set Environment Variables from GitHub Secrets
        run: |
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV

      - name: Run the script
        env:
          DISPLAY: ":99"  # Required for Selenium in headless mode
        run: python pelosi_trader.py
